### ISSUE TITLE
PSHubCore - occupied slot in the hotbar

### ISSUE THREAD

**Issue by Monty70** [arcadiadevs/playerservers-everything#3]
Even if I turn off the insertion of "selector" items in config.yml and "player menu" to the hotbar, the position set in the cfg cannot be used in the game.

```
gui:
  selector:
    item:
      enabled: false
      name: '&aQuick Compass'
      material: COMPASS
      location: 0
```

```
  player-menu:
    item:
      enabled: false
      name: '&eMy Player Server'
      material: EMERALD
      location: 1
```
In my case it is slots 0 and 1, see video

https://streamable.com/ii62gd
paper 1.18.2
